### ISSUE TITLE
Fill PMF in JavaScript

### ISSUE THREAD

**Issue by E4tHam** [ucsbieee/arcade-pong#1]
# Fill PMF in JavaScript

## Issue Description

Fill the PMF with the sprites in [resources/](https://github.com/ucsbieee/arcade-pong/tree/main/resources). The game file is [pong.js](https://github.com/ucsbieee/arcade-pong/blob/main/high-level/src/pong.js).

## Help

* [JavaScript Guide](https://arcade.ucsbieee.org/guides/javascript/)
* [GPU Guide](https://arcade.ucsbieee.org/guides/gpu/)

Feel free to add to any of the guides if you run into difficulties you want to warn others about.

Here is an example of a completed game: [game-demo.js](https://github.com/ucsbieee/arcade/blob/main/high-level/tests/game-demo.js).

**Comment by kermitnak** [comment]
branch is fill-PMF
