### ISSUE TITLE
Drawing Scores

### ISSUE THREAD

**Issue by E4tHam** [ucsbieee/arcade-pong#4]
# Drawing Scores

## Issue Description

There is a function in [pong.js](https://github.com/ucsbieee/arcade-pong/blob/main/high-level/src/pong.js) called `draw_scores()`. This function should fill the NTBL according to `leftScore` and `rightScore`. Note, the range these numbers can take on is 0-11.

It should look like [this](https://images.app.goo.gl/TJ2VbwD6mHERCbU46).

The PFB will only have two tiles: [`number_corner`](https://github.com/ucsbieee/arcade-pong/blob/main/resources/tiles/number_corner.png) and [`number_edge`](https://github.com/ucsbieee/arcade-pong/blob/main/resources/tiles/number_edge.png). Use [numbers.png](https://github.com/ucsbieee/arcade-pong/blob/main/resources/metatiles/numbers.png) as a reference for how to arrange the tiles into numbers.

## Help

* [JavaScript Guide](https://arcade.ucsbieee.org/guides/javascript/)
* [GPU Guide](https://arcade.ucsbieee.org/guides/gpu/)

Feel free to add to any of the guides if you run into difficulties you want to warn others about.

Here is an example of a completed game: [game-demo.js](https://github.com/ucsbieee/arcade/blob/main/high-level/tests/game-demo.js).

**Comment by ArthurG0** [comment]
In review by @E4tHam , some cleanup regarding event listeners required.
